networks:
  traefik_traefik_proxy:
    external: true
    # Failure to provide the correct external network name results in:
    # Error response from daemon: failed to set up container networking: invalid cluster node while attaching to network
    name: traefik_traefik_proxy

volumes:
    home-assistant-matter-hub:
      driver: local
      driver_opts:
        type: nfs4
        o: addr=172.24.32.5,rw
        device: ":/srv/nfs4/docker_nfs/matter-hub/"

services:
  matter-hub:
    image: ghcr.io/t0bst4r/home-assistant-matter-hub:3.0.0-alpha.95
    restart: unless-stopped
    network_mode: host
    # networks:
    #   - traefik_proxy
    env_file:
      - .env
    volumes:
      - home-assistant-matter-hub:/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_traefik_proxy
      - traefik.http.routers.matter-hub.rule=Host(`matter-hub.viewpoint.house`) || Host(`172.24.32.13`)
      - traefik.http.routers.matter-hub.entrypoints=web
      - traefik.http.services.matter-hub.loadbalancer.server.port=8482
      - traefik.http.services.matter-hub.loadbalancer.healthcheck.path=/
      - traefik.http.services.matter-hub.loadbalancer.healthcheck.port=8482